# Generated by Django 4.0.6 on 2022-07-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='order_items',
            options={'verbose_name': 'Заказ запчасти', 'verbose_name_plural': 'Заказы запчастей'},
        ),
    ]
