# Generated by Django 4.0.6 on 2022-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_changed_order_created_order_items_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
