# Generated by Django 4.0.6 on 2022-07-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_carmodel_carsubmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='PartSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.partcategory')),
            ],
            options={
                'verbose_name': 'Вид запчасти',
                'verbose_name_plural': 'Виды запчастей',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SlugField(max_length=250)),
                ('seller_name', models.CharField(max_length=250)),
                ('seller_phone', models.CharField(max_length=16, unique=True)),
                ('seller_email', models.EmailField(max_length=254)),
                ('car_submodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carsubmodel')),
                ('part_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.partsubcategory')),
            ],
            options={
                'verbose_name': 'Информация о товаре',
            },
        ),
    ]
