# Generated by Django 4.0.6 on 2022-07-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Информация о товаре', 'verbose_name_plural': 'Информация о товарах'},
        ),
    ]
