# Generated by Django 4.0.6 on 2022-07-21 11:06

from django.db import migrations


def PartCategory(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PartCategory = apps.get_model('parts', 'PartCategory')
    PartCategory.objects.all()

def PartSubCategory(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PartSubCategory = apps.get_model('parts', 'PartSubCategory')
    PartSubCategory.objects.all()

def Parts(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Parts = apps.get_model('parts', 'Parts')
    Parts.objects.all()

    
class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_partcategory_changed_partcategory_created_and_more'),
    ]

    operations = [
        migrations.RunPython(PartCategory),
        migrations.RunPython(PartSubCategory),
        migrations.RunPython(Parts),
    ]
