# Generated by Django 4.0.6 on 2022-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20220721_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcategory',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='partsubcategory',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
