# Generated by Django 4.0.6 on 2022-07-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_alter_partcategory_created_alter_parts_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='seller_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
