# Generated by Django 4.0.6 on 2022-07-20 12:59

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tariff_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Наценка', 'verbose_name_plural': 'Наценка на товары'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userphone',
        ),
        migrations.AddField(
            model_name='tariff',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='invalid email')]),
        ),
    ]
