# Generated by Django 4.0.6 on 2022-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tariff_options_remove_user_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
