# Generated by Django 4.0.6 on 2022-07-21 11:19

from django.db import migrations

def User(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Order = apps.get_model('users', 'User')
    Order.objects.all()

def Tariff(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Tariff = apps.get_model('users', 'Tariff')
    Tariff.objects.all()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tariff_created'),
    ]

    operations = [
        migrations.RunPython(User),
        migrations.RunPython(Tariff),
    ]
