# Generated by Django 4.0.6 on 2022-07-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
            },
        ),
        migrations.CreateModel(
            name='Auto_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Модель')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.auto', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Запчасть')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.auto', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='Part_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Дополнительно')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.part', verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='Auto_SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Подмодель')),
                ('automodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.auto_model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Подмодель',
            },
        ),
    ]
