# Generated by Django 4.0.6 on 2022-07-21 10:30

from django.db import migrations


def data_migrate(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CarMark = apps.get_model('cars', 'CarMark')
    CarMark.objects.all()

def data_migrate(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CarModel = apps.get_model('cars', 'CarModel')
    CarModel.objects.all()

def data_migrate(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CarSubModel = apps.get_model('cars', 'CarSubModel')
    CarSubModel.objects.all()


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_changed_carmodel_created_and_more'),
    ]

    operations = [
        migrations.RunPython(data_migrate),
    ]
