# Generated by Django 4.0.6 on 2022-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20220721_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmark',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='carsubmodel',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
